### PR TITLE
Adds Travis CI config file, resolves #14

### LINKED ISSUE #14: Provide continuous integration
Once we have tests for this project (https://github.com/adolorosa/BoredGamers/issues/13) and code linters and formatters (https://github.com/adolorosa/BoredGamers/issues/10, https://github.com/adolorosa/BoredGamers/issues/9) we want to enforce them and make sure every single commit we do passes these automated checks.

One way of doing this is setting up continuous integration, e.g. TravisCI.

Let's look into TravisCI, enable it for this project, and then have it
- install our dependencies
- run code linters and formatters
- run tests

If all of these stages pass, TravisCI will give green light, and we can confidently merge pull requests.

Tasks
- [ ] on the TravisCI page connect this repository and enable it
- [ ] provide a `.travis.yml` configuration file for TravisCI with the stages listed above

### PR DESCRIPTION
**Pull request by daniel-j-h**
For #14: this adds a Travis CI config file which tells the continuous integration workers to install our requirements and then just print something for now. We test this on both Python 3.6 as well as 3.7 since these seem reasonable versions to support for now.

Down the road we want to add our linters, code formatters, and tests here. Then Travis CI will run them all on every single commit and pull request we do and tell us if we are good to go or not.

@adolorosa you have to go to the Travis CI page, log in with your Github account, and connect this repository and enable it. Then we can test it by pushing another commit to this branch. Ping me when you enabled it. Thanks!

### CODE REVIEW

**Comment by adolorosa** [comment]
I connected my repo and enabled it on the Travis CI page. What do I do next?

**Comment by daniel-j-h** [comment]
I just pushed another commit but it seems like Travis is not picking it up. Can you make sure you this repository being enabled in Travis CI, I think it should be here:

https://travis-ci.org/adolorosa/BoredGamers

and in its settings (to the right: More Options -> Settings) you may need to enable 
- Build Pushed Branches
- Build Pushed Pull Requests

**Comment by adolorosa** [comment]
I checked, both are enabled. What about the travis.yml file, doesn't it need to be in my repository first?

**Comment by daniel-j-h** [comment]
Hm, yes you can try it. Merge this pull request. Then create a new one where you push a single simple commit, and you should see the Travis worker building the pull request.

**Comment by daniel-j-h** [comment]
It works now! Check out https://travis-ci.org/adolorosa/BoredGamers

If you put the following into the readme you will get a badge where you see if master is working or not

```
[![Build Status](https://travis-ci.org/adolorosa/BoredGamers.svg?branch=master)](https://travis-ci.org/adolorosa/BoredGamers)
```

And in addition every time you create a new pull request you will find a Travic worker at the bottom running your project and then reporting success or failure. The idea is then to make tests run in the `.travis.yml` script so that for every commit you can be sure it's not breaking master and only merge if everything is green. Give it a try! :)

**Comment by adolorosa** [comment]
Yup, it works :) Thanks!

**Pull request merged**
